[settings]
dotfiles.root = "~/.mise-dotfiles"

[bootstrap.mise_shell_activate]
bashrc = "activate"

[bootstrap.services.mise-history]
builtin = "history-watch"

[dotfiles]
"~/.bash_profile" = { mode = "track" }
"~/.bashrc" = { mode = "track" }
"~/.config/mise" = { mode = "track" }
"~/.config/nvim" = { mode = "track" }
"~/.config/ghostty" = { mode = "track", exclude = ["config.local"] }

[tools]
d2 = "latest"
go = "1.27"
neovim = "0.12.5"
node = "24"
terraform = "1.16"
tree-sitter = "latest"
