[settings]
dotfiles.root = "~/.mise-dotfiles"

[bootstrap.mise_shell_activate]
bashrc = "activate"

[bootstrap.services.mise-history]
builtin = "history-watch"

[dotfiles]
"~/.bash_profile" = { mode = "track" }
"~/.bashrc" = { mode = "track" }
"~/.config/mise" = { mode = "track" }

[tools]
go = "1.27"
jq = "1.8.2"
neovim = "0.12.5"
node = "24"
tree-sitter = "latest"
